# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
      with:
        working-directory: "./native/"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
    - name: Run gradle test with XVFB
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run --auto-servernum gradle test
    - name: Run gradle test
      if: matrix.os != 'ubuntu-latest'
      run: gradle test
    - run: |
        cd native
        cargo build --release
        cd ..
    - name: Upload library
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{ matrix.os }}
        path: ./native/target/release/*.*

  jar:
    
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
      with:
        working-directory: "./native/"
    - run: cargo install cross
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Download all build artifacts
      uses: actions/download-artifact@v2.1.0
      with:
        path: ./lib/build/resources/main/natives/
    - run: |
        cd ./lib/build/resources/main/natives
        ls ./
        find . -type f -mindepth 2 -maxdepth 3 -exec mv -i -n -- {} . \;
        find . -depth -maxdepth 0 -type d -exec rm -r {} \;
        ls ./
        cd ../../../../../
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: jar --info
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: ./lib/build/libs/
    
    
